# Generated by Django 4.0 on 2021-12-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('mark', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10)),
                ('max_mark', models.IntegerField()),
                ('method_name', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
