# Generated by Django 4.0 on 2022-02-21 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionComposite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubQuestionComposite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.IntegerField()),
                ('description', models.TextField()),
                ('method_name', models.TextField()),
                ('max_mark', models.IntegerField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questioncomposite')),
            ],
        ),
    ]
