# Generated by Django 4.0.2 on 2022-03-16 13:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_questioncomposite_subquestioncomposite'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subquestioncomposite',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
