# Generated by Django 4.0.2 on 2022-03-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_timestarted'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncomposite',
            name='part_name',
            field=models.TextField(default='l'),
            preserve_default=False,
        ),
    ]
