# Generated by Django 4.0.2 on 2022-04-10 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_remove_questioncomposite_part_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
