# Generated by Django 4.0.2 on 2022-04-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeStarted',
        ),
    ]
