<<<<<<< HEAD
# Generated by Django 4.0 on 2022-01-03 16:19
=======
# Generated by Django 4.0 on 2022-01-03 21:33
>>>>>>> 32b5e96 (adding static lint display)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticLint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
<<<<<<< HEAD
                ('feedback', models.TextField(blank=True, null=True)),
=======
                ('feedback', models.TextField()),
>>>>>>> 32b5e96 (adding static lint display)
            ],
        ),
    ]
