# Generated by Django 4.0.2 on 2022-03-16 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_alter_submission_managers_and_more'),
        ('static_lint', '0005_alter_staticlint_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticlint',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.submission'),
        ),
    ]
