# Generated by Django 4.0 on 2022-03-16 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0003_questioncomposite_subquestioncomposite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_number', models.IntegerField()),
                ('submission_time', models.DateTimeField()),
                ('sub_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.subquestioncomposite')),
            ],
        ),
    ]
