# Generated by Django 4.0.2 on 2022-03-16 13:12

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='submission',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
