# Generated by Django 4.0.2 on 2022-03-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_alter_submission_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='answer',
            field=models.TextField(default='l'),
            preserve_default=False,
        ),
    ]
