# Generated by Django 4.0.2 on 2022-04-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_submission_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStarted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
