# Generated by Django 4.0.2 on 2022-04-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_timestarted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='submission',
            managers=[
            ],
        ),
    ]
