number: 1
description: "The scenario for this question is about computing scores in a heptathlon event. For simplicity we are
              focusing only on the track events, the 200 metres, the 800 metres, and the 110 metres hurdles."