number: 1
part: 2
description: "The scenario for this question is about computing the score of an athlete in a given track event. We need
to convert a time in seconds into points. The official formula is:
<div>points = a(b - time)^c <i>(Equation 1)</i></div>
<br>
where <i>time</i> is the time in seconds of the athlete for that event. <i>a</i>, <i>b</i> and <i>c</i> are parameters
that vary depending on the event (see Table 1 below). The value of points must be rounded down to a whole number after
applying the respective formula (e.g. 499.999 points becomes 499).
<br>
<div>.</div>
<table>
  <tr>
    <td>Women's events</td>
    <td>a</td>
    <td>b</td>
    <td>c</td>
  </tr>
  <tr>
    <td>200m</td>
    <td>4.99087</td>
    <td>42.5</td>
    <td>1.81</td>
  </tr>
  <tr>
    <td>800m</td>
    <td>0.11193</td>
    <td>254.0</td>
    <td>1.88</td>
  </tr>
  <tr>
    <td>110m</td>
    <td>9.23076</td>
    <td>26.7</td>
    <td>1.835</td>
  </tr>
</table>
<div><i>Table 1: Constants </i>a<i>, </i>b<i> and </i>c<i> for each event</i></div>
<br>
Write a function <b>track_points(time, event_parameters)</b> which takes a <b>str</b> parameter <b>time</b>
representing the athlete's time following the format given in part i, and a tuple containing the event's
parameters. The method returns an <b>int</b> representing the points scored for that event using Equation 1.
In addition, the method always returns a value greater or equal to 0, that is if the result of Equation 1
is negative, the points must be rounded to 0.
<br>
<div>For example:</div>
<ul>
  <li>
    a time of 22.830 seconds in the 200 metres corresponds to 1,096 points,
  </li>
  <li>
    a time of 45.000 seconds in the 200 metres corresponds to 0 points (not a negative value),
  </li>
  <li>
    a time of 12.540 seconds in the 110 metres hurdles corresponds to 1,195 points,
  </li>
  <li>
    a time of 128.650 seconds (i.e. 02:08.650) in the 800 metres corresponds to 984 points,
  </li>
  <li>
  	a time of 255 seconds (i.e. 04:15.000) in the 800 metres corresponds to 0 points  (not a negative value).
  </li>
</ul>

The function must raise a <b>ValueError</b> if the time format does not follow the format given in part i. It
should also raise a <b>ValueError</b> if the tuple does not contain exactly 3 float values.
"
max_mark: 15
part_name: Event's Score
method_name: track_points
